### PR TITLE
add footer

### PR DESCRIPTION
**Pull request by Drapegnik**

### CODE REVIEW

**Comment by Drapegnik** [comment]
@darjanska footer looks ugly, i think style should be improved

**Comment by darjanska** [comment]
@Drapegnik well, can you make your claims&propositions a little bit more clear? what's the problem? fonts? colors? grid?

**Comment by Drapegnik** [comment]
@darjanska sorry for delay, was busy.
screen shot 2017-09-18 at 11 20 05

more clearly:
1. it looks very empty, not enough content for that size
2. telegram icon, you should find some way to replace it (`swg`, custom font, some addition for font-awesome - please google it)
3. email form - for that functionality not implemented by backend and not planned in first time, so you should find way how prettily hide it (more problems with empty space)

**Comment by Drapegnik** [comment]
for example: http://ilyabirman.net/projects/likely/

**Pull request merged**
