### PR TITLE
Footer redesign

### PR DESCRIPTION
**Pull request by tyndria**
screencapture-localhost-3001-main-page-main-page-html-1514214712564

### CODE REVIEW

**Comment by tyndria** [comment]
@UladBohdan, does it look confusing?

**Comment by UladBohdan** [comment]
@tyndria slightly, yes

**Comment by tyndria** [comment]
@UladBohdan , ok, thanks, I will think about it

**Comment by Drapegnik** [comment]
[improve footer markup](https://trello.com/c/9WrwD4QV/40-improve-footer-markup)

**Pull request merged**
