### PR TITLE
Make node module:

### PR DESCRIPTION
**Pull request by tyndria**
1. Add .npmignore
2. Update readme
3. Add prepublish, postpublish scripts
4. Add style to sign up page for testing
*** Delete postinstall because of error during installation this package

### CODE REVIEW

**Comment by Drapegnik** [comment]
what problem with `postinstall`? it executed after `npm i babajka-markup`?

**Comment by tyndria** [comment]
@Drapegnik , yes, as I understood, after installing package he try to run build, but gulp is ignored (because we ignore all files except of css) , so it fails

**Comment by Drapegnik** [comment]
maybe it right we need? we can npmignore our build files, and publish `gulp` and after install in frontend, `postinstall` make build?

**Comment by Drapegnik** [comment]
and if we can somehow downgrade version? to `0.0.2` for example

**Comment by tyndria** [comment]
Yes, it could be so. It's not really important. 
Frankly, I don't know about versions, will check it

**Comment by Drapegnik** [comment]
[publish markup repo as npm package, and add is as dependency of frontend project](https://trello.com/c/S3iedwB4/19-publish-markup-repo-as-npm-package-and-add-is-as-dependency-of-frontend-project)

**Pull request merged**
