### PR TITLE
About page

### PR DESCRIPTION
**Pull request by UladBohdan**
Currently discussing the page with Maša.

### CODE REVIEW

**Comment by UladBohdan** [comment]
['about' page markup](https://trello.com/c/rrbCRDOq/105-about-page-markup)

**Comment by Drapegnik** [comment]
some remarks:
* imho this separator should be full-width:
screen shot 2018-03-27 at 16 05 03

* is any `active` state for this buttons or it just like on `hover`?
screen shot 2018-03-27 at 16 05 16

**Comment by UladBohdan** [comment]
* I specifically made the separator of non-full width.
* As for now there's no `active` state although that is discussible, we may add it.

We'll talk more about design itself once I figure out all the details of the page (content details) with Maša.

**Comment by UladBohdan** [comment]
Not perfect, but it does not need to be perfect at the moment.
I am about to merge it.

**Pull request merged**
